#require:
#  - rubocop-performance
#  - rubocop-thread_safety
#  - rubocop-i18n
#  - rubocop-md
#  - rubocop-rails
#  - rubocop-rake
#  - rubocop-rspec
#  - rubocop-sequel
#  - rubocop/require_tools

### rubocop-i18n
# You *must* choose GetText or Rails-i18n style checking
# If you want GetText-style checking
#GetText:
#  Enabled: true
#RailsI18n:
#  Enabled: false
## If you want rails-i18n-style checking
#RailsI18n:
#  Enabled: true
#GetText:
#  Enabled: false
AllCops:
  NewCops: enable
  ParserEngine: parser_prism
  StringLiteralsFrozenByDefault: true

Layout/LineLength:
  Max: 80
