#!/usr/bin/env bash

if [ -f "$(command -v rougify)" ]; then
    highlighter='rougify --theme monokai'
elif [ -f "$(command -v pygmentize)" ]; then
    highlighter='pygmentize -f 256'
else
  exit 1
fi

case "$1" in
    *.awk|*.groff|*.java|*.js|*.m4|*.php|*.pm|*.pod|*.sh|\
    *.ad[asb]|*.asm|*.inc|*.[ch]|*.[ch]pp|*.[ch]xx|*.cc|*.hh|\
    *.lsp|*.l|*.pas|*.p|*.xml|*.xps|*.xsl|*.axp|*.ppd|*.pov|\
    *.css|*.go|*.html|*.json|*.lua|*.markdown|*.md|*.rs|*.tex|\
    *.viml|*.yaml|*.sed|*.jl|*.hs|*.erl|*.ex|*.exs|*.eex|*.leex|\
    *.swift|*.kts|*.cr|*.lisp|*.scm|*.scss|*.sass|*.vala|\
    *.cs|*.diff|*.patch|*.py|*.rb|*.sql|*.ebuild|*.eclass)
        $highlighter "$1";;

    .bashrc|.bash_aliases|.bash_environment|.lessfilter)
        $highlighter -l sh "$1";;

    *.pl)
        $highlighter -l perl "$1";;

    Gemfile|Rakefile|*.ru)
        $highlighter -l ruby "$1";;

    Dockerfile)
        $highlighter -l docker "$1";;

    *)
        exit 1
esac

exit 0
