#!/usr/bin/env bash

set -e

# Regenerate tags
.git/hooks/ctags >/dev/null 2>&1 &

# List files to commit and number of file in commit
files=$(git status -s | grep -E 'A|M|U' | awk '{print $NF}' | tr '\n' ' ')
nb_of_files=$(echo "$files" | wc -w)

#echo -n "Would you like to run Rubocop & Reek ? (y|N)"
#read yn
#case $yn in
#  [yY] | [yY][Ee][Ss] )
#    run_rubocop;
#    ;;
#  [nN] | [n|N][O|o])
#    ;;
#esac
#
#function run_rubocop() {
#  # If file to commit, run Rubocop and Reek
#  if [[ "$nb_of_files" -gt 0 ]]; then
#    echo -e "Rubocop:"
#    rubocop $files
#    echo -e "\nReek:"
#    reek $files
#  fi
#}

## Generate Gemfile.lock
#[ ! -f Gemfile ] || git diff --exit-code --cached -- Gemfile >/dev/null || bundle check

# Run default precommit hook
#exec "$(git --exec-path)/../../share/git-core/templates/hooks/pre-commit.sample"

rubocop .
