export LDFLAGS="-L/opt/homebrew/opt/openssl@3/lib"
export CPPFLAGS="-I/opt/homebrew/opt/openssl@3/include"
export PKG_CONFIG_PATH="/opt/homebrew/opt/openssl@3/lib/pkgconfig"
export LDFLAGS="$LDFLAGS -L/opt/homebrew/opt/libpq/lib"
export CPPFLAGS="$CPPFLAGS -I/opt/homebrew/opt/libpq/include"
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/opt/homebrew/opt/libpq/lib/pkgconfig"
source "$HOME/.cargo/env"
